config/routes.rb
Rails.application.routes.draw do
  devise_for :mememasters, path_names: { sign_in: 'login'}
  resources :mememasters, only: [:show]
  resources :packs, only: [:new, :create, :destroy]
  

  root 'application#home'

end

app/models/mememaster.rb
class Mememaster < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable
  has_many :packs
end

app/models/pack.rb
class Pack < ActiveRecord::Base
	belongs_to :mememaster
	validates :c1, presence: true
	validates :c2, presence: true
	validates :c3, presence: true
	validates :c4, presence: true
	validates :c5, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def after_sign_in_path_for(resource)
    
    stored_location_for(resource) || mememaster_path(current_mememaster) || root_path
    
  end



  def home
  end
end

app/controllers/mememasters_controller.rb
class MememastersController < ApplicationController
	

	def show
  	@user = Mememaster.find(params[:id])
  	@packs = current_mememaster.packs.build
  	getnums

	end

	private

	


	def getnums
		@commons = 0
		@rares = 0
		@mythicals = 0
		@legendaries = 0
		@commonsg = 0
		@raresg = 0
		@mythicalsg = 0
		@legendariesg = 0

		@allpacks = @user.packs.all
		@packscards= (@allpacks.count*5)
		
		for i in @allpacks
			if i.c1 == "common" && i.c1g
				@commonsg += 1
			elsif i.c1 == "common" && !i.c1g
				@commons += 1
			elsif i.c1 == "rare" && i.c1g
				@raresg += 1
			elsif i.c1 == "rare" && !i.c1g
				@rares += 1
			elsif i.c1 == "mythical" && i.c1g
				@mythicalsg += 1
			elsif i.c1 == "mythical" && !i.c1g
				@mythicals += 1
			elsif i.c1 == "legendary" && i.c1g
				@legendariesg += 1
			elsif i.c1 == "legendary" && !i.c1g
				@legendaries += 1
			end
			
			if i.c2 == "common" && i.c2g
				@commonsg += 1
			elsif i.c2 == "common" && !i.c2g
				@commons += 1
			elsif i.c2 == "rare" && i.c2g
				@raresg += 1
			elsif i.c2 == "rare" && !i.c2g
				@rares += 1
			elsif i.c2 == "mythical" && i.c2g
				@mythicalsg += 1
			elsif i.c2 == "mythical" && !i.c2g
				@mythicals += 1
			elsif i.c2 == "legendary" && i.c2g
				@legendariesg += 1
			elsif i.c2 == "legendary" && !i.c2g
				@legendaries += 1
			end
			
			if i.c3 == "common" && i.c3g
				@commonsg += 1
			elsif i.c3 == "common" && !i.c3g
				@commons += 1
			elsif i.c3 == "rare" && i.c3g
				@raresg += 1
			elsif i.c3 == "rare" && !i.c3g
				@rares += 1
			elsif i.c3 == "mythical" && i.c3g
				@mythicalsg += 1
			elsif i.c3 == "mythical" && !i.c3g
				@mythicals += 1
			elsif i.c3 == "legendary" && i.c3g
				@legendariesg += 1
			elsif i.c3 == "legendary" && !i.c3g
				@legendaries += 1
			end
			
			if i.c4 == "common" && i.c4g
				@commonsg += 1
			elsif i.c4 == "common" && !i.c4g
				@commons += 1
			elsif i.c4 == "rare" && i.c4g
				@raresg += 1
			elsif i.c4 == "rare" && !i.c4g
				@rares += 1
			elsif i.c4 == "mythical" && i.c4g
				@mythicalsg += 1
			elsif i.c4 == "mythical" && !i.c4g
				@mythicals += 1
			elsif i.c4 == "legendary" && i.c4g
				@legendariesg += 1
			elsif i.c4 == "legendary" && !i.c4g
				@legendaries += 1
			end
			
			if i.c5 == "common" && i.c5g
				@commonsg += 1
			elsif i.c5 == "common" && !i.c5g
				@commons += 1
			elsif i.c5 == "rare" && i.c5g
				@raresg += 1
			elsif i.c5 == "rare" && !i.c5g
				@rares += 1
			elsif i.c5 == "mythical" && i.c5g
				@mythicalsg += 1
			elsif i.c5 == "mythical" && !i.c5g
				@mythicals += 1
			elsif i.c5 == "legendary" && i.c5g
				@legendariesg += 1
			elsif i.c5 == "legendary" && !i.c5g
				@legendaries += 1
			end
			
		end

		@pcommons = (@commons.to_f/@packscards)*100
		@prares = (@rares.to_f / @packscards) * 100
		@pmythicals = (@mythicals.to_f / @packscards) * 100
		@plegendaries = (@legendaries.to_f / @packscards) * 100

		
	end

end

app/controllers/packs_controller.rb
class PacksController < ApplicationController
  before_action :authorize, only: :destroy

  def new
    @pack = Pack.new()
  end

	def create
    @packs = current_mememaster.packs.build(micropost_params)
    if @packs.save
      respond_to do |format|
        format.html { redirect_to mememaster_path(current_mememaster) }
        format.js
      end
    else
      flash[:danger] = "fuck you"
      redirect_to mememaster_path(current_mememaster)
    end

  end

  def destroy
    @pack = Pack.find(params[:id])
    @pack.destroy
    respond_to do |format|
        format.html { redirect_to mememaster_path(current_mememaster) }
        format.js
    end
  end

  private

    def micropost_params

        params.require(:pack).permit(:c1,:c2,:c3,:c4,:c5,:c1g,:c2g,:c3g,:c4g,:c5g)



    end



    def authorize
    redirect_to root_url unless current_mememaster == Pack.find(params[:id]).mememaster
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mememasters_helper.rb
module MememastersHelper
end

app/helpers/packs_helper.rb
module PacksHelper
end

app/views/application/home.html.erb
<div class="container">
	<div class="jumbotron">
		<h1>Hearthstone packs tracker</h1>
		<p>Para ver si tenes suerte o no, yo que se</p>
		<% if !mememaster_signed_in? %>
			<%= link_to 'Login', new_mememaster_session_path,class: 'btn btn-primary btn-lg' %>
			<%= link_to 'Registrarse', new_mememaster_registration_path,class: 'btn btn-primary btn-lg' %>
		<% else %>
			<%= link_to 'Ir a mi cuenta', mememaster_path(current_mememaster),class: 'btn btn-primary btn-lg' %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hearth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'part/header' %>

<div class="container">
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
</div>

<%= yield %>

</body>
</html>

app/views/mememasters/_pack.html.erb
<div id="pack<%= @packs.id %>">
	<div class="created"><%= @packs.created_at.to_s.first(10) %></div>
		<div class="carta"><%= @packs.c1 %></div>
		<div class="carta"><%= @packs.c2 %></div>
		<div class="carta"><%= @packs.c3 %></div>
		<div class="carta"><%= @packs.c4 %></div>
		<div class="carta"><%= @packs.c5 %></div>
		<% if current_mememaster == Mememaster.find(params[:id]) %>
		<%= link_to "Eliminar", @packs,class: "delete",remote: true, method: :delete  %>
		<% end %>
</div>

app/views/mememasters/_table_current.html.erb
<table class="table table-hover">
	<tr>
		<th>Tipo de carta</th>
		<th>Cantidad</th>
		<th>Porcentaje</th>
		<th>Polvito</th>
	</tr>
	<tr>
		<td>Comunes</td>
		<td><%= @commons + @commonsg %> (<%= @commonsg %>)</td>
		<td><%= @pcommons.round(2) %> %</td>
		<td><%= @commons * 5 + @commonsg * 50 %></td>
	</tr>
	<tr>
		<td>Raras</td>
		<td><%= @rares + @raresg %> (<%= @raresg %>)</td>
		<td><%= @prares.round(2) %> %</td>
		<td><%= @rares * 20 + @raresg * 100 %></td>
	</tr>
	<tr>
		<td>Epicas</td>
		<td><%= @mythicals + @mythicalsg %> (<%= @mythicalsg %>)</td>
		<td><%= @pmythicals.round(2) %> %</td>
		<td><%= @mythicals * 100 + @mythicalsg * 400 %></td>
	</tr>
	<tr>
		<td>Legendarias</td>
		<td><%= @legendaries + @legendariesg %> (<%= @legendariesg %>)</td>
		<td><%= @plegendaries.round(2) %> %</td>
		<td><%= @legendaries * 400 + @legendariesg * 1600 %></td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Total</td>
		<td><%= @commons * 5 + @rares * 20 + @mythicals * 100 + @legendaries * 400 + @commonsg * 50 + @raresg * 100 + @mythicalsg * 400 + @legendariesg * 1600 %></td>
	</tr>
</table>

app/views/mememasters/_table_static.html.erb
<table class="table table-hover">
	<tr>
		<th>Tipo de carta</th>
		<th>Probabilidad individual</th>
		<th>Probabilidad por pack</th>
	</tr>
	<tr>
		<td>Comun</td>
		<td>71.30%</td>
		<td>99.81%</td>
	</tr>
	<tr>
		<td>Rara</td>
		<td>23.10%</td>
		<td>73.11%</td>
	</tr>
	<tr>
		<td>Epica</td>
		<td>4.30%</td>
		<td>19.73%</td>
	</tr>
	<tr>
		<td>Legendaria</td>
		<td>1.30%</td>
		<td>6.33%</td>
	</tr>

</table>

app/views/mememasters/show.html.erb
<div class="container">



<div class="row">

<div class="col-sm-5 col-xs-12 col-sm-push-7">

<%= link_to "Nuevo pack",new_pack_path,data: {disable_with: "..."}, remote: true, class: "btn btn-primary", id: "new_link" %>
<div class="infotable">
<div class="counttotal"><%= pluralize(@user.packs.all.count,"Pack")%></div>

<%= render "table_current" %>

</div>
<%= render "table_static" %>

 </div>
<div class="col-sm-7 col-xs-12 col-sm-pull-5">
<div id="cartas">
<% @user.packs.reverse.each do |thing| %>
		<div id="pack<%= thing.id %>">
		<div class="created"><%= thing.created_at.to_s.first(10) %></div>
		<% if thing.c1g %>
			<div class="cartag"><%= thing.c1 %></div>
		<% else %>
			<div class="carta"><%= thing.c1 %></div>
		<% end %>

		<% if thing.c2g %>
			<div class="cartag"><%= thing.c2 %></div>
		<% else %>
			<div class="carta"><%= thing.c2 %></div>
		<% end %>

		<% if thing.c3g %>
			<div class="cartag"><%= thing.c3 %></div>
		<% else %>
			<div class="carta"><%= thing.c3 %></div>
		<% end %>

		<% if thing.c4g %>
			<div class="cartag"><%= thing.c4 %></div>
		<% else %>
			<div class="carta"><%= thing.c4 %></div>
		<% end %>

		<% if thing.c5g %>
			<div class="cartag"><%= thing.c5 %></div>
		<% else %>
			<div class="carta"><%= thing.c5 %></div>
		<% end %>

		<% if current_mememaster == Mememaster.find(params[:id]) %>
		<%= link_to "Eliminar", thing,class: "delete",remote: true, method: :delete  %>
		<% end %>
		</div>
		<% end %>
		</div>
</div>

</div>

</div>
</div>

app/views/packs/_form.html.erb
<%= form_for @pack, remote: true do |f| %>
  <div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary">
    <%= f.radio_button :c1,"common", type: "radio" %> Común
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c1,"rare", type: "radio", :checked %> Rara
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c1,"mythical", type: "radio" %> Epica
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c1,"legendary", type: "radio" %> Legendaria
    </label>
    
    <%= f.check_box :c1g, {}, true, false%>
    <%= f.label :c1g, "Gold" %>
    
  </div>
  
    <div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary">
    <%= f.radio_button :c2,"common", type: "radio", :checked %> Común
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c2,"rare", type: "radio" %> Rara
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c2,"mythical", type: "radio" %> Epica
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c2,"legendary", type: "radio" %> Legendaria
    </label>

    <%= f.check_box :c2g, {}, true, false%>
    <%= f.label :c2g, "Gold" %>
  </div>
    <div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary">
    <%= f.radio_button :c3,"common", type: "radio", :checked %> Común
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c3,"rare", type: "radio" %> Rara
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c3,"mythical", type: "radio" %> Epica
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c3,"legendary", type: "radio" %> Legendaria
    </label>

    <%= f.check_box :c3g, {}, true, false%>
    <%= f.label :c3g, "Gold" %>

  </div>
    <div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary">
    <%= f.radio_button :c4,"common", type: "radio", :checked %> Común
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c4,"rare", type: "radio" %> Rara
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c4,"mythical", type: "radio" %> Epica
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c4,"legendary", type: "radio" %> Legendaria
    </label>

    <%= f.check_box :c4g, {}, true, false%>
    <%= f.label :c4g, "Gold" %>

  </div>
    <div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary">
    <%= f.radio_button :c5,"common", type: "radio", :checked %> Común
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c5,"rare", type: "radio" %> Rara
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c5,"mythical", type: "radio" %> Epica
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c5,"legendary", type: "radio" %> Legendaria
    </label>

    <%= f.check_box :c5g, {}, true, false%>
    <%= f.label :c5g, "Gold" %>

    </div>
 
    
  <%= f.submit "Listo", data: {disable_with: "Procesando"}, class: "btn btn-primary" %>

  <% end %>

app/views/packs/_pack.html.erb
<div id="pack<%= @packs.id %>">
	<div class="created"><%= @packs.created_at.to_s.first(10) %> Nuevo!</div>
		<% if @packs.c1g %>
			<div class="cartag"><%= @packs.c1 %></div>
		<% else %>
			<div class="carta"><%= @packs.c1 %></div>
		<% end %>		
		<% if @packs.c2g %>
			<div class="cartag"><%= @packs.c2 %></div>
		<% else %>
			<div class="carta"><%= @packs.c2 %></div>
		<% end %>
		<% if @packs.c3g %>
			<div class="cartag"><%= @packs.c3 %></div>
		<% else %>
			<div class="carta"><%= @packs.c3 %></div>
		<% end %>
		<% if @packs.c4g %>
			<div class="cartag"><%= @packs.c4 %></div>
		<% else %>
			<div class="carta"><%= @packs.c4 %></div>
		<% end %>
		<% if @packs.c5g %>
			<div class="cartag"><%= @packs.c5 %></div>
		<% else %>
			<div class="carta"><%= @packs.c5 %></div>
		<% end %>
		
		<%= link_to "Eliminar", @packs,class: "delete",remote: true, method: :delete  %>
		
</div>

app/views/packs/new.html.erb
<%= form_for(@pack) do |f| %>
  <div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary">
    <%= f.radio_button :c1,"common", type: "radio" %> Común
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c1,"rare", type: "radio" %> Rara
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c1,"mythical", type: "radio" %> Epica
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c1,"legendary", type: "radio" %> Legendaria
    </label>
  </div>
  
    <div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary">
    <%= f.radio_button :c2,"common", type: "radio" %> Común
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c2,"rare", type: "radio" %> Rara
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c2,"mythical", type: "radio" %> Epica
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c2,"legendary", type: "radio" %> Legendaria
    </label>
  </div>
    <div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary">
    <%= f.radio_button :c3,"common", type: "radio" %> Común
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c3,"rare", type: "radio" %> Rara
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c3,"mythical", type: "radio" %> Epica
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c3,"legendary", type: "radio" %> Legendaria
    </label>
  </div>
    <div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary">
    <%= f.radio_button :c4,"common", type: "radio" %> Común
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c4,"rare", type: "radio" %> Rara
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c4,"mythical", type: "radio" %> Epica
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c4,"legendary", type: "radio" %> Legendaria
    </label>
  </div>
    <div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary">
    <%= f.radio_button :c5,"common", type: "radio" %> Común
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c5,"rare", type: "radio" %> Rara
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c5,"mythical", type: "radio" %> Epica
    </label>
    <label class="btn btn-primary">
    <%= f.radio_button :c5,"legendary", type: "radio" %> Legendaria
    </label>
    </div>
 

  <%= f.submit "Listo", data: {disable_with: "Procesando"}, class: "btn btn-primary" %>

  <% end %>

app/views/part/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Heartstone Track", root_path, class:"navbar-brand" %>
    </div>
	<ul class="nav navbar-nav">
    <li>
    <%= link_to 'Mi dashboard', mememaster_path(current_mememaster) unless !mememaster_signed_in? %>
    </li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
	<li>	
	<%= link_to 'Logout', destroy_mememaster_session_path, method: :delete unless !mememaster_signed_in? %>
    </li>
    </ul>
      </div>
</nav>

app/views/part/_pack.html.erb
<div id="pack<%= @packs.id %>">
	<div class="created"><%= @packs.created_at.to_s.first(10) %></div>
		<div class="carta"><%= @packs.c1 %></div>
		<div class="carta"><%= @packs.c2 %></div>
		<div class="carta"><%= @packs.c3 %></div>
		<div class="carta"><%= @packs.c4 %></div>
		<div class="carta"><%= @packs.c5 %></div>
		<% if current_mememaster == Mememaster.find(params[:id]) %>
		<%= link_to "Eliminar", @packs,class: "delete",remote: true, method: :delete  %>
		<% end %>
</div>